name: MSBuild

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      BUILD_CONFIGURATION: ${{matrix.configuration}}
      
      # Path to the solution file relative to the root of the project.
      SOLUTION_FILE_PATH: ./mhw-cs-plugin-loader.sln

      # Allow vcpkg to install packages from the NuGet binary cache.
      USERNAME: Fexty12573
      VCPKG_EXE: vcpkg
      FEED_URL: https://nuget.pkg.github.com/Fexty12573/index.json
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/Fexty12573/index.json,readwrite"

    steps:
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v8
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: "[,17)"
          msbuild-architecture: x64

      - name: Integrate vcpkg
        run: |
          vcpkg integrate install

      - name: Add vcpkg nuget sources
        shell: pwsh
        run: |
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            sources add `
            -Source "${{ env.FEED_URL }}" `
            -StorePasswordInClearText `
            -Name GitHubPackages `
            -UserName "${{ env.USERNAME }}" `
            -Password "${{ secrets.VCPKG_PAT_TOKEN }}"
          .$(${{ env.VCPKG_EXE }} fetch nuget) `
            setapikey "${{ secrets.VCPKG_PAT_TOKEN }}" `
            -Source "${{ env.FEED_URL }}"

      - name: Generate cimgui project files
        run: |
          cmake -S ${{ env.CIMGUI_ROOT }} -B ${{ env.CIMGUI_ROOT }} -G "Visual Studio 17 2022"
        env:
          CIMGUI_ROOT: dependencies/cimgui
      
      - name: Dotnet Restore
        run: |
          dotnet restore ${{ env.SOLUTION_FILE_PATH }}
      
      - name: Build Solution
        run: |
          msbuild -m -p:Configuration=${{ env.BUILD_CONFIGURATION }} -p:Platform=x64 ${{ env.SOLUTION_FILE_PATH }}

      - name: Compute Short Git Hash
        id: compute_hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

      - name: Make Package
        if: matrix.configuration == 'Release'
        id: make_package
        run: |
          python ./make-package.py -c Release --msbuild-in-path . ${{ steps.compute_hash.outputs.sha_short }}
          echo "package_win32=SharpPluginLoader-${{ steps.compute_hash.outputs.sha_short }}-win32.zip" >> $env:GITHUB_OUTPUT
          echo "package_linux=SharpPluginLoader-${{ steps.compute_hash.outputs.sha_short }}-linux.zip" >> $env:GITHUB_OUTPUT
      
      # Upload release-files/tags/<short_sha>/SharpPluginLoader-<short_sha>-(win32|linux).zip
      - name: Upload win32 Package Artifact
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.make_package.outputs.package_win32 }}
          path: release-files/tags/${{ steps.compute_hash.outputs.sha_short }}/${{ steps.make_package.outputs.package_win32 }}

      - name: Upload linux Package Artifact
        if: matrix.configuration == 'Release'
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.make_package.outputs.package_linux }}
          path: release-files/tags/${{ steps.compute_hash.outputs.sha_short }}/${{ steps.make_package.outputs.package_linux }}

      # TODO(Andoryuuta): Can't currently build solution directly due to build order issues + "Release" mode binaries expected on-disk for some build scripts.
      # - name: Build Solution
      #   working-directory: ${{env.GITHUB_WORKSPACE}}
      #   # Add additional options to the MSBuild command line here (like platform or verbosity level).
      #   # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      #   run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=x64 /p:VcpkgEnableManifest=true ${{env.SOLUTION_FILE_PATH}}
